### ISSUE TITLE
[error] failed post-processing

### ISSUE THREAD

**Issue by miparnisari** [lyft/protoc-gen-star#102]
I'm very new to Go and protoc in general. Can I get help with this issue? https://stackoverflow.com/questions/70360041/error-failed-post-processing-82039-missing-in-argument-list/70390311

tl;dr a build is failing and i'm pretty sure the error is being emitted in this package but i don't have enough information to debug 😭

**Comment by pdecks** [comment]
Howdy 👋🏻  Looking at your SO post and your linked [`protoc-gen-validate` PR](https://github.com/envoyproxy/protoc-gen-validate/pull/546), I'm not sure how this is an issue with PG* if you haven't ruled out a bug in `protoc-gen-validate` first. There seems to be a similar existing bug in `protoc-gen-validate`: https://github.com/envoyproxy/protoc-gen-validate/issues/276

**Comment by miparnisari** [comment]
@pdecks thanks for fast response! I don't think there's an issue with PG*, but i'd like to know how to debug this, since it looks like because of this error none of the `*.pb.validate.go` files are being created, so I can't see where the syntax error is

**Comment by miparnisari** [comment]
Never mind, I found the problem in my PR...
