### ISSUE TITLE
Generating custom files in the same directory as protoc

### ISSUE THREAD

**Issue by SonarBeserk** [lyft/protoc-gen-star#20]
I am working on a project that requires generating .ico files as well as text files. Previously I used AddGeneratorTemplateFile to generate from a template, however with the new utf-8 validation this is no longer possible. AddCustomTemplateFile allows the file to be generated but the issue is that it is generated in the wrong directory. The output path is constantly returned as "." regardless of what the protoc parameters are set to.

**Comment by rodaine** [comment]
This is a limitation of `protoc`, where plugins are not given the output path from the execution (the value after the `:`). PG* supports setting a [`output_path` param](https://godoc.org/github.com/lyft/protoc-gen-star#Parameters.OutputPath) to override this behavior. So your protoc execution should look something like the following:

```bash
protoc \
  myplugin_out="output_path=${OUTPUT}:${OUTPUT}"\
  my_proto.proto
```

**Comment by pdecks** [comment]
From what I can tell, this feature doesn't actually work. I've had to add a separate parameter to pass a path, and using `output_path` has no effect.
