### ISSUE TITLE
Access `reserved` fields in protoc plugins

### ISSUE THREAD

**Issue by dotReduce** [lyft/protoc-gen-star#22]
Hi, first off thanks for all the amazing work that was put into this.  It makes code-gen great again!

Apologies if this is not the appropriate medium for this question, but is there any way to extract `reserved` fields from protoc-gen-star?  I am generating a `*.service.proto` file from a `.proto` and would like to translate the reserved fields from the original proto over.

Thanks!

**Comment by rodaine** [comment]
Hey, glad you're enjoying! The reserved tag numbers and names are accessible off the descriptor. So you could do the following:

```go
var msg pgs.Message
msg.Descriptor().GetReservedRange() // for the ranges of tag numbers reserved
msg.Descriptor().GetReservedName() // for the reserved names
```
The ranges are a [repeated message type](https://godoc.org/github.com/golang/protobuf/protoc-gen-go/descriptor#DescriptorProto_ReservedRange) while the names are a repeated string.

Hope that helps!

**Comment by dotReduce** [comment]
Fantastic - appreciate the quick response!
