### ISSUE TITLE
Expose CodeGeneratorResponse's Error field

### ISSUE THREAD

**Issue by srenatus** [lyft/protoc-gen-star#34]
In the [definition of `CodeGeneratorResponse`](https://github.com/protocolbuffers/protobuf/blob/a6e1cc7e328c45a0cb9856c530c8f6cd23314163/src/google/protobuf/compiler/plugin.proto#L98), we find

```proto
  // Error message.  If non-empty, code generation failed.  The plugin process
  // should exit with status code zero even if it reports an error in this way.
  //
  // This should be used to indicate errors in .proto files which prevent the
  // code generator from generating correct code.  Errors which indicate a
  // problem in protoc itself -- such as the input CodeGeneratorRequest being
  // unparseable -- should be reported by writing a message to stderr and
  // exiting with a non-zero status code.
optional string error = 1;
```

This seems very useful, and seems like it would often be the better choice compared to calling `m.Fail()` and friends. However, unless I'm mistaken, setting this field from a module isn't something PGS lets you do. Am I missing something?

In our concrete usecase, unit testing PGS-based code generators, it would be simpler to check this field, compared to having a test case end up calling `os.Exit(1)`.

**Comment by rodaine** [comment]
Makes sense! This would be great as a new `Artifact` type instead of building in a different side effect.

**Comment by srenatus** [comment]
@rodaine I gave this a go ☝️ 😃
