### ISSUE TITLE
Proto file lacking a package can result in processing failure

### ISSUE THREAD

**Issue by nick-jones** [lyft/protoc-gen-star#42]
## Description

This appears to occur when the library attempts to resolve message field types, where the type is non-scalar and not defined within a package.

From what I can tell, this may down to the fact that the [fullyQualifiedName()](https://github.com/lyft/protoc-gen-star/blob/95ca57a4ef989c084ed1a5a58810d2b34a28cf72/name.go#L184) function looks to include the FQN of the parent. The parent can have return FQN of `.` - so this function can return something along the lines of `..Foo`. When [hydrating field types](https://github.com/lyft/protoc-gen-star/blob/95ca57a4ef989c084ed1a5a58810d2b34a28cf72/ast.go#L284), an FQN value derived from the field is passed down - where no package is specified, this will have a value along the lines of `.Foo`. The mismatch results in Failf() being called.

## Steps to reproduce

Create proto file containing no package declaration:

```
$ mkdir testdata/protos/nopackage/
$ cat > testdata/protos/nopackage/foo.proto <<EOF
syntax = "proto3";

message Foo {
    uint64 id = 1;
}

message Bar {
    Foo foo = 1;
}
EOF
```

Make testdata target:

```
$ make testdata
<snip>
# generate using our demo plugin, don't need to go directory at a time
set -e; for subdir in `find ./testdata/protos -type d -mindepth 1 -maxdepth 1`; do \
                protoc -I ./testdata/protos \
                        --plugin=protoc-gen-example=./bin/protoc-gen-example \
                        --example_out="paths=source_relative:./testdata/generated" \
                        `find $subdir -name "*.proto"`; \
        done
expected entity ".Foo" has not been hydrated
--example_out: protoc-gen-example: Plugin failed with status code 1.
make: *** [testdata/generated] Error 1

```

**Comment by rodaine** [comment]
Doh, I thought I fixed this in a different patch, but I guess I didn't. Thanks for the report!
