### ISSUE TITLE
Does not properly escape package names

### ISSUE THREAD

**Issue by wdullaer** [lyft/protoc-gen-star#55]
The packagename sanitation pgs performs is not equivalent to the official go plugin logic.
The official plugin will also escape package names starting with numbers and package names containing dashes.

As an example: `2019-awesome-package` becomes `_2019_awesome_package`

You already seem to escape if the packagename is a go keyword over here:
https://github.com/lyft/protoc-gen-star/blob/master/lang/go/package.go#L27-L30

I suppose this logic needs to be extended.

(I encountered this issue when trying to use validate rules, which seems to rely on this code for that part of the code generation)

**Comment by wdullaer** [comment]
Here's the relevant implementation in protoc-gen-go
https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L640

**Comment by rodaine** [comment]
Fixed by #56
