### ISSUE TITLE
Full google.protobuf.SourceCodeInfo?

### ISSUE THREAD

**Issue by peter-edge** [lyft/protoc-gen-star#6]
I saw you just added comment support from the SourceCodeInfos in https://github.com/lyft/protoc-gen-star/commit/6f176a97c8cfa3e7d164b0115ade1fd6d9aff49d, what about extending this to include line and column information? This would be useful, especially in the visitor.

**Comment by glerchundi** [comment]
@peter-edge can you explain a use-case in which this would be useful? Now that the parsing methodology is in place it's fairly easy to include this. I can take this one but once we decide a real use-case and an appropriate API for it.

**Comment by glerchundi** [comment]
Reference documentation: https://github.com/google/protobuf/blob/1a7a7fca804afa1cf67f8be5e71092898ba40334/src/google/protobuf/descriptor.proto#L788-L793

**Comment by peter-edge** [comment]
I’m writing a self-contained linter and formatter for protobuf, that right now relies on github.com/emicklei/proto, but using the tried-and-tested proto parser in protoc would be ideal.

I would/might write this myself but don’t want to reinvent the wheel as you all have done such a great job here.
