### ISSUE TITLE
Options support

### ISSUE THREAD

**Issue by peter-edge** [lyft/protoc-gen-star#7]
Or rather full support for google.protobuf.FileDescriptorSet, every field on the FileDescriptorProtos -is this on the roadmap?

**Comment by rodaine** [comment]
The `FileDescriptor` is accessible from [`pgs.File#Descriptor()`](https://godoc.org/github.com/lyft/protoc-gen-star#File), encapsulated within the protoc-gen-go `generator.FileDescriptor`.

closing this in favor of having the discussion about FileDescriptorSet in #10
