### ISSUE TITLE
insertAppend does not respect insertion order

### ISSUE THREAD

**Issue by jagobagascon** [lyft/protoc-gen-star#73]
When using several append type artifacts on the same file the order of the artifacts is not respected by the persister.

```go
resp := p.Persist(
  GeneratorFile{
    Name:     "file",
    Contents: "foo",
  },
  GeneratorAppend{
    FileName: "file",
    Contents: "bar",
  },
  GeneratorAppend{
    FileName: "file",
    Contents: "end",
  },
)
```

The above code should result in a file with the content `foobarend` but the result is `fooendbar` instead. This happens because the method `insertAppend` is looking for the file using `indexOfFile` which always returns the index of the first match (`0` in this case).

I added a fix proposal and a test that replicates this problem in #74.

**Comment by rodaine** [comment]
Closed by #74
